name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:

  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        run: |
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo apt-get clean
          sudo apt-get autoclean
          sudo apt-get update
          sudo apt-get -y install containerd
          sudo apt install -y docker.io docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Set up Docker
      - name: Log in to Docker Hub
        run: |
          echo "Logging in to Docker Hub with username: ${{ secrets.DOCKERHUB_USER }}"
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Verify project contents
        run: |
          ls -la

      - name: Build and push Docker image
        run: |
          cd tennis-table-booking-reservation
          docker build -t rafagomezp/tt-sant-andreu-reservation:${{ github.sha }}  -f Dockerfile .
          docker push rafagomezp/tt-sant-andreu-reservation:${{ github.sha }}

  deploy_to_digital_ocean:
    runs-on: ubuntu-latest
    needs: [create-docker-image]
    steps:
      - name: Install sshpass
        run: sudo apt-get -y install sshpass

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          debug: true
          script: |
            container_id=$(docker ps -aqf "ancestor=rafagomezp/tt-sant-andreu-andreu-reservation")
            echo "Container ID: $container_id"
            docker stop $container_id
            docker rm $container_id
            docker pull rafagomezp/tt-sant-andreu-reservation:${{ github.sha }}
            docker run -d --name tt-sant-andreu-reservation -p 80:80 rafagomezp/tt-sant-andreu-reservation:${{ github.sha }}
