name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:

  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get -y remove moby-containerd containerd moby-runc runc
          sudo apt-get -y install docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Log in to Docker Hub
        run: |
          echo "Logging in to Docker Hub with username: ${{ secrets.DOCKERHUB_USER }}"
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t rafagomezp/tt-sant-andreu-reservation:${{ github.sha }} .
          docker push rafagomezp/tt-sant-andreu-reservation:${{ github.sha }}

  deploy_to_digital_ocean:
    runs-on: ubuntu-latest
    needs: [create-docker-image]
    steps:
      - name: Install sshpass
        run: sudo apt-get -y install sshpass

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          script: |
            docker pull rafagomezp/tt-sant-andreu-reservation:${{ github.sha }}
            docker stop my-angular-app || true
            docker rm my-angular-app || true
            docker run -d --name my-angular-app -p 80:80 rafagomezp/tt-sant-andreu-reservation:${{ github.sha }}
